### ISSUE TITLE
Progress from calls such as PullImage

### ISSUE THREAD

**Issue by ibuildthecloud** [samalba/dockerclient#136]
I'd like to print progress of the `PullImage`.  I'm willing to do the PR but would like some guidance on the approach.  Do we break the current API, new API?  Does the API accept a chan and blocks, should it return immediatly and not block.....  Just give me a method signature and I'll implement it :)

**Comment by pault84** [comment]
Would love this feature aswell, also in that api can we return the ID of the newly pulled image?

**Comment by odewahn** [comment]
Same here -- I'm working on a GUI tool that lets you pull images and I'd love to be able to show a percent complete / progress bar.
