### ISSUE TITLE
Cut the dependency to docker/docker

### ISSUE THREAD

**Issue by ahmetalpbalkan** [samalba/dockerclient#155]
It looks like using this library requires vendoring the entire docker/docker repo which is suboptimal.

The package is only uses the docker/docker repo in the following files:

`types.go`:

* `github.com/docker/docker/pkg/units`: only for `units.HumanDuration`, actually the client should not tamper the results that are received from the API. I'm not sure why we're trying to produce strings like `Exited %s ago` in this repo... This is not docker cli.

`engine_mock_test.go`, `dockerclient_test.go`:

* `github.com/docker/docker/pkg/jsonlog`: Just to construct a jsonlog-looking-like type. We can copy the type over here to do the same.
* `github.com/docker/docker/pkg/stdcopy`: to do NewStdWriter, we can copy the logic here.
* `github.com/docker/docker/pkg/ioutils`: uses NewFlushWriter, sounds like we  can copy that here too.

What do maintainers think? I have a 60-line project that uses this `samalba/dockerclient` but I ended up vendoring 225,000+ lines of go code (only in `docker/docker`).

IMO we should cut the dependency to `docker/docker` ASAP.

**Comment by abronan** [comment]
Hi @ahmetalpbalkan! You don't need to vendor the entire repo (at least if you use Godep), take a look at swarm and the Godeps, we only include the needed `pkg` from docker :)

We can still get rid of the dependency though.. to avoid any confusion and the `pkg` used here are pretty lightweight anyway..

**Comment by ahmetalpbalkan** [comment]
I ended up getting rid of dockerclient dependency and just vendored `docker/docker/pkg/tlsconfig` as I was using only one endpoint in my project. My argument is, godep etc will always work in this case, but here we can probably eliminate the dependency to `docker/docker` which would be one less thing to worr about.

**Comment by tve** [comment]
I'm also finding the fact that importing dockerclient imports the rest of the docker world rather annoying. I'm using glide for the Go pkg management and it traverses the dependency tree resulting in a huge increase in CI times due to all the packages that need to be downloaded and installed. Any thoughts?

**Comment by ahmetalpbalkan** [comment]
@tve you can check out https://github.com/fsouza/go-dockerclient alternatively.

**Comment by samalba** [comment]
It sucks that we depend on docker/docker pkgs. When I started this lib a
while ago, it was exactly because fsouza's was vendoring part of docker.

We should fix this.


On Monday, December 14, 2015, Ahmet Alp Balkan <notifications@github.com>
wrote:

> @tve <https://github.com/tve> you can check out
> https://github.com/fsouza/go-dockerclient alternatively.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samalba/dockerclient/issues/155#issuecomment-164616711>
> .
>


-- 
Sam Alba
Sr. Director of Engineering
Docker, inc

**Comment by thaJeztah** [comment]
@samalba work is in progress to improve this, ask @calavera for more info if needed.

**Comment by cmarcelo** [comment]
@calavera do you have more information about this?

**Comment by thaJeztah** [comment]
@cmarcelo have a look at https://github.com/docker/engine-api/

**Comment by allingeek** [comment]
Maybe this is part of the ViP but can we replace references to dockerclient/types with github.com/docker/engine-api/types/types ?

**Comment by tve** [comment]
was this fixed? or deemed irrelevant? or ?
