### ISSUE TITLE
Example for docker run -v and -e

### ISSUE THREAD

**Issue by aminjam** [samalba/dockerclient#204]
I am looking for an example of using `--volume` with `ContainerConfig`. I see there is a `Volumes         map[string]struct{}` in `ContainerConfig`, but how do I use it? 

Also I can't find any example for using `-e` option. I have tried setting `Env` array item to be `NAME=AJ`. What should be the format for `Env` slice in `ContainerConfig`?

**Comment by odewahn** [comment]
Hi, @aminjam.  Did you ever find this or figure it out?  I'm looking for the same thing and haven't had any luck find an example, either.
