### ISSUE TITLE
Update API Version to 1.22

### ISSUE THREAD

**Issue by nishanttotla** [samalba/dockerclient#227]
Corresponding with the Docker 1.10 release, we need to update API Version for `dockerclient` to `1.22`. Creating this issue to track and discuss any changes that need to be made to support the updated API.

cc @dongluochen @vieux

**Comment by vieux** [comment]
I would rather switch swarm to engine-api

**Comment by dongluochen** [comment]
If it requires extra compatibility testing/review, we should drop it. Switch to engine-api in next release makes more sense.

**Comment by nishanttotla** [comment]
@vieux @dongluochen  I agree, but it didn't seem like we have a plan in place to do that right now. I can take the initiative on that by making a list of changes needed in Swarm so we can drop `dockerclient` completely. Closing this issue, thanks.
