### ISSUE TITLE
Deprecate in favour of docker/engine-api

### ISSUE THREAD

**Issue by bfirsh** [samalba/dockerclient#238]
A bunch of projects use this library, so we probably shouldn't abandon it, but it would perhaps be sensible to suggest people try using https://github.com/docker/engine-api instead.

Is there anything missing from docker/engine-api that would stop users from being able to use it instead of this library?

/cc @samalba @vieux

**Comment by vieux** [comment]
I would say event management, it's pretty rough in https://github.com/docker/engine-api

**Comment by bfirsh** [comment]
@vieux Specifically what about event management is lacking? I want to open an issue against docker/engine-api about this, but not sure exactly what to say. :)

**Comment by vieux** [comment]
@bfirsh all the complicated code here https://github.com/samalba/dockerclient/blob/master/dockerclient.go#L472 that parses events and return them via channel, etc...

last time I looked the only thing in engine-api was a `GET /events` but you have to do most of the rest by hand

**Comment by vdemeester** [comment]
@bfirsh @vieux yeah, the `events` in `engine-api` is pretty bare-metal. I've created a library [docker-events](https://github.com/vdemeester/docker-events) (that we use in `libcompose`) to make it a little useful and was wondering if we should have some code like that in `engine-api`.

**Comment by bfirsh** [comment]
@vieux @vdemeester Thanks, this is really helpful.

@vdemeester Agreed something like that should probably be in engine-api. I've opened https://github.com/docker/engine-api/issues/246 to keep track.
