### ISSUE TITLE
boot2docker and TLS

### ISSUE THREAD

**Issue by mg** [samalba/dockerclient#59]
Hi, Im getting the following error when connecting to docker (running with boot2docker on OSX) with dockerclient:

```
Get http://192.168.59.103:2376/v1.15/images/json: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
```

The docs at http://golang.org/pkg/crypto/tls/#Config don't really tell me how I should fill out the tls.Config structure to work with docker/boot2docker. Do you have any examples on how to do this?

**Comment by hongweiyi** [comment]
LGTM

When using docker-machine, the TLS file path is: `$HOME/.docker/machine/certs/`
