### ISSUE TITLE
support docker rm -v

### ISSUE THREAD

**Issue by bradrydzewski** [samalba/dockerclient#73]
I could definitely use support for the `docker rm -v` option to remove all volumes associated with the container. This is particularly useful when working with data volume containers over a remote connection.

Would you be willing to accept a pull request implementing this change? I was thinking something like the following:

```diff
-func RemoveContainer(id string, force bool)
+func RemoveContainer(id string, force, volumes bool)
```

**Comment by samalba** [comment]
:+1:

**Comment by bradrydzewski** [comment]
@samalba fyi opened pull request #74 for this. Let me know if you need anything else!
